### ISSUE TITLE
[Bug] Forced rules are not fetched when `WithForcedVariations(growthbook.ForcedVariationsMap{})` is in the context

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook-golang#15]
### Summary

Initial fetching of features doesn't fetch forced rules when adding `WithForcedVariations(growthbook.ForcedVariationsMap{})` in the context.

#### Expected Behavior

Forced rules **should be** fetched when `WithForcedVariations(growthbook.ForcedVariationsMap{})` is in the context.

#### Current Behavior

Forced rules **are not fetched** when `WithForcedVariations(growthbook.ForcedVariationsMap{})` is in the context.

#### More info
https://growthbookusers.slack.com/archives/C01T6PKD9C3/p1694505434135549

**Comment by ian-ross** [comment]
For context, this is from the Slack conversation about this issue:

----
Hi Pratik, To follow up on the other question you had about `WithForcedVariations`. I don't understand what the results you're expecting here are. I'll try to give some sort of explanation of what I think is going on, and you can tell me where it doesn't match what you're seeing.

There are two distinct "forced" things you can do with the Go SDK (the other language SDKs behave in a similar way). You can force **rules for features**, which you set up on the GrowthBook site with conditions that say "if a user satisfies these conditions, then **force** them to have this **value** for this **feature**". I'm pretty sure that works correctly, since I use it for testing all the time.

The `WithForcedVariations` thing is a separate mechanism that allows you to force the variation returned for an experiment. I think people mostly use it for QA purposes, since it allows you to examine what happens in your code when a particular experiment outcome happens. The code paths that reference this stuff don't influence the features that are downloaded by `LoadFeatures` and they only have an effect on experiment outcomes if the particular experiment key is in the forced variations map. Setting the forced variations map to an empty map shouldn't have any impact on anything at all.

Can you confirm that you really are seeing a difference in the **feature rules** when you use `WithForcedVariations`?

Just to give some context:

Here is the code that implements `WithForcedVariations`, which just sets the forced variations map on the context: https://github.com/growthbook/growthbook-golang/blob/main/context.go#L107-L113

And here is the place where the forced variations map is referenced (in the `doRun` method which actually runs experiments and is called from `EvalFeature`) — if the map is non-empty _and_ the experiment key is in the map, then the experiment _variation_ (i.e. the integer index into the list of possible outcomes) is taken from the map: https://github.com/growthbook/growthbook-golang/blob/main/growthbook.go#L726-L734

Forcing of _rules_ is handled here in `EvalFeature` — if a forcing rule exists for a user in the feature, then the forced value is returned immediately, without constructing and running an experiment for the feature (which means the forced variations map is never used in this code path): https://github.com/growthbook/growthbook-golang/blob/main/growthbook.go#L423-L444

The forced variations map isn't referenced anywhere else, so I can't see how it's possible for it to influence the effect of forcing rules.

I hope this helps us get some way to understanding what's happening in your case!

**Comment by august-growthbook** [comment]
Thank you very much for your reply, Ian.

**Comment by darkLord19** [comment]
@ian-ross Thanks a lot for clarification. So basically my issue is like following.

I have a feature named let's say `test-feature-1` which has default value as false.
I have added forced values for condition `if uId = x then serve true` but the issue I am facing is even when uId is x, it is returning false instead of true.

**Comment by ian-ross** [comment]
@darkLord19 Hmmm. That sounds strange. I do this for testing all the time, and I've never seen it fail to work. As an example, below I've included what I get from the GrowthBook features API endpoint for one of my test cases (you can look at the same sort of thing by getting `https://cdn.growthbook.io/api/features/<your SDK key>`).

I have a feature called `banner_text` with a default value (in English), and forcing rules that depend on the `country` attribute. The forced values for the `country = "france"` and `country = "spain"` cases work, and can be updated via streaming updates as well. (I just checked that it really is working. This is used in the example [here](https://github.com/growthbook/examples/blob/main/go-example/acme_handler.go).)

Can you see anything different in the way I have things set up compared to what you're doing?

```json
{
    "dateUpdated": "2023-09-17T11:33:11.033Z",
    "features": {
        "banner_text": {
            "defaultValue": "Welcome to Acme Donuts! (TEST)",
            "rules": [
                {
                    "condition": {
                        "country": "france"
                    },
                    "force": "Bienvenue au Beignets Acme ! (TEST)"
                },
                {
                    "condition": {
                        "country": "spain"
                    },
                    "force": "¡Bienvenidos y bienvenidas a Donas Acme! (TEST)"
                }
            ]
        }
    },
    "status": 200
}
```

**Comment by ian-ross** [comment]
Some other thoughts:

- If you call `LoadFeatures` without setting `AutoRefresh`, then call `LoadFeatures` again, it will return cached items from the feature repository even if they are stale (this behavior is copied from the JavaScript SDK). If you want to force a refresh, you can use the `RefreshFeatures` method instead.
- If you're using `AutoRefresh` and you have streaming updates set up on your SDK connection, then you should just get new feature definitions automatically. (You can confirm definitively that your SDK connection is set up correctly by looking at the HTTP response from your `https://cdn.growthbook.io/api/features/<sdk-key>` endpoint. If the response has a header that says `x-sse-support: enabled` then streaming updates should work.)

**Comment by darkLord19** [comment]
@ian-ross upon further debugging had found that it was code issue from our end and after fixing it this issue has been resolved so can close this issue. Sorry for false alert. 😓

**Comment by ian-ross** [comment]
@darkLord19 Thanks for letting us know!
